#!/bin/sh
# 获取当前分支名
branch=$(git symbolic-ref --short HEAD)
# 如果当前分支不是 main（或 master）分支，则不执行自动提交代码逻辑
if [ "$branch" != "main" ] && [ "$branch" != "master" ]; then
  exit 0
fi
# 添加修改的文件到暂存区
git add .
# 提交代码并附加默认消息
git commit -m "Auto commit"
# 推送代码到远程仓库
git push origin "$branch"